# ----------------------------------------------------------------------
# Config for theme: Creative
# ----------------------------------------------------------------------

baseurl             = "https://aviariesdepot.com"
languageCode        = "en-au"
title               = "Aviaries Depot"
theme               = "creative"
googleAnalytics     = "UA-111712204-3"
paginate            = 12

[taxonomies]
  category = "categories"
  tag = "tags"

[params]

    name                    = "Aviaries Depot"
    favicon                 = "favicon.png"

    description             = "Keeping your furry friends entertained and Active while preserving your beloved furniture from their sharp claws, Aviaries Depot for scratch problems"

	# Navigation
	[params.navigation]
		brand = "Aviaries Depot"
		brand_logo = "img/logo-40h.png"

		[params.navigation.links]
			about     			= "About"
			testimonials    	= "Testimonials"
			services  			= "Services"
			portfolio 			= "More Info"
			contact   			= "Contact"
			blog				= "News"

	# Blog
	[params.blog]
		path = "/news"

	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = ""
		subtitle   = ""
		buttonText = ""


	# About section
	[params.about]
		headline    = "Bird Cages suitable for your need and preferences"
		description = "We provide many types of cages for your bird which is safe, durable, and more importantly spacious to allow them to fly around freely."
		buttonText  = ""

	# Footer
	[params.footer]
		headline    = ""
		description = "Looking for secure cages for your feathered friends but don't want them to feel trapped and cramped in a small space?  Contact us for a solution that is suitable for your needs."

	# Testimonials
	[params.testimonials]
		headline    = "What our customers are saying..."


	# Service section
	[params.services]
		headline = "Our Promise"

        [[params.services.list]]
            icon = "fa-truck"
            title = "Quick & Easy Shipping"
            description_x = "Easy door to door deliveries."

        [[params.services.list]]
			icon = "fa-money"
			title = "Price Match Guarantee"
			description_x = "Price match guarantee on our instore products!"

		[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Hassel Free Returns"
            description_x = "Let us deal with it for you."

        [[params.services.list]]
            icon = "fa-phone"
            title = "Dedicated support"
            description_x = "Talk with our operators!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	# [params.aside]
	# 	headline = "Expert Advice"

	# 	[params.aside.button]
	# 		text = "Download now"
	# 		link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	# [params.contact]
	# 	headline = "Let's Get In Touch!"
	# 	description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
	# 	phone = "123-456-6789"
	# 	email = "feedback@startbootstrap.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
